### ISSUE TITLE
Doesn't work with display-line-numbers-mode

### ISSUE THREAD

**Issue by XO39** [jcs-elpa/line-reminder#7]
@jcs090218 Can you make it work with `display-line-numbers-mode` as well? `display-line-numbers-mode` [displays numbers in the text area](https://www.reddit.com/r/emacs/comments/aa9rg7/how_to_make_line_numbers_in/ecq7nub/?utm_source=reddit&utm_medium=web2x&context=3) after the left fringe, so when disabling `linum-mode` and enabling `display-line-numbers-mode` instead, the `line-reminder` is gone.

And BTW, `display-line-numbers-mode` [is much faster than](https://www.reddit.com/r/emacs/comments/aa9rg7/how_to_make_line_numbers_in/ecqha74/?utm_source=reddit&utm_medium=web2x&context=3) `linum-mode`

**Comment by jcs090218** [comment]
I am currently using `display-line-numbers-mode` with `indicators`. You can enabled it by setting `line-reminder-show-option` to symbol `'indicators`. There are few issue with indicator since other package may overwrite the indicator symbol. e.g. `flycheck`. Yet this is currently the best solution. 😕

**Comment by jcs090218** [comment]
And I assumed indicators can only be render on the left which will make this quite different from using `linum-mode`.

**Comment by XO39** [comment]
> I am currently using `display-line-numbers-mode` with `indicators`. You can enabled it by setting `line-reminder-show-option` to symbol `'indicators`. There are few issue with indicator since other package may overwrite the indicator symbol. e.g. `flycheck`. Yet this is currently the best solution. 😕

Yes, it works with `'indecators`, I needed to restart emacs though, that's why I thought it doesn't work when I used `'indicators` before asking this question.

`flycheck` indeed overwrites the indicator, but I can live with that for now as flycheck is more critical for me.

Good to know you are aware of this issue, so this issue should be closed (as it's somehow solves the problem)?

**Comment by jcs090218** [comment]
> Yes, it works with 'indecators, I needed to restart emacs though, that's why I thought it doesn't work when I used 'indicators before asking this question.

Ah, sorry about that! You do need to restart Emacs or call `M-x line-reminder` once again.

> so this issue should be closed (as it's somehow solves the problem)?

I will close this issue now. Feel free to open another issue about flycheck overwrites indicators though. 👍
